//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NetOperateLog> NetOperateLog { get; set; }
        public virtual DbSet<NetSysFunc> NetSysFunc { get; set; }
        public virtual DbSet<NetSysRole> NetSysRole { get; set; }
        public virtual DbSet<NetSysUser> NetSysUser { get; set; }
        public virtual DbSet<NetTenant> NetTenant { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<TrainingCard> TrainingCard { get; set; }
        public virtual DbSet<TrainingCheckin> TrainingCheckin { get; set; }
        public virtual DbSet<TrainingSignUp> TrainingSignUp { get; set; }
        public virtual DbSet<TrainingTimes> TrainingTimes { get; set; }
        public virtual DbSet<TrainingVerificationCode> TrainingVerificationCode { get; set; }
    }
}
