//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetSysFunc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NetSysFunc()
        {
            this.NetSysFunc1 = new HashSet<NetSysFunc>();
            this.NetSysRole = new HashSet<NetSysRole>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OrderNumber { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> ParentFuncId { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsTenantFunc { get; set; }
        public int FuncType { get; set; }
        public bool IsDisplay { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetSysFunc> NetSysFunc1 { get; set; }
        public virtual NetSysFunc NetSysFunc2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NetSysRole> NetSysRole { get; set; }
    }
}
